// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.1'

        classpath 'com.google.gms:google-services:4.5.0'
        classpath 'com.google.firebase:perf-plugin:2.0.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.6'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
